version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"

  backend:
    build: ./backend
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
