version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "9000:90"

  backend:
    build: ./backend
    ports:
      - "9000:90"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
