version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
